environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
      TARGET: x86_64-pc-windows-msvc
    - PYTHON: "C:\\Python36-x64"
      TARGET: x86_64-pc-windows-msvc

branches:
  only:
  - develop
  - master

cache:
  # Cache downloaded pip packages and built wheels.
  - '%LocalAppData%\pip\Cache\http'
  - '%LocalAppData%\pip\Cache\wheels'

install:
  - git submodule update --init --recursive
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -e .[test] --verbose"

build: false

test_script:
  - "%PYTHON%\\python.exe -m snips_nlu download snips_nlu_de-0.2.0 --direct"
  - "%PYTHON%\\python.exe -m snips_nlu download snips_nlu_en-0.2.0 --direct"
  - "%PYTHON%\\python.exe -m snips_nlu download snips_nlu_es-0.2.0 --direct"
  - "%PYTHON%\\python.exe -m snips_nlu download snips_nlu_fr-0.2.0 --direct"
  - "%PYTHON%\\python.exe -m snips_nlu download snips_nlu_ja-0.2.0 --direct"
  - "%PYTHON%\\python.exe -m snips_nlu download snips_nlu_ko-0.2.0 --direct"
  - "%PYTHON%\\python.exe -m snips_nlu download snips_nlu_zh-0.2.0 --direct"
  - "%PYTHON%\\python.exe -m snips_nlu link snips_nlu_de de"
  - "%PYTHON%\\python.exe -m snips_nlu link snips_nlu_en en"
  - "%PYTHON%\\python.exe -m snips_nlu link snips_nlu_es es"
  - "%PYTHON%\\python.exe -m snips_nlu link snips_nlu_fr fr"
  - "%PYTHON%\\python.exe -m snips_nlu link snips_nlu_ja ja"
  - "%PYTHON%\\python.exe -m snips_nlu link snips_nlu_ko ko"
  - "%PYTHON%\\python.exe -m snips_nlu link snips_nlu_zh zh"
  - "%PYTHON%\\python.exe -m unittest discover"
  - "%PYTHON%\\python.exe snips_nlu_samples/sample.py"
